name       : python-tox
version    : 3.24.4
release    : 15
source     :
    - https://github.com/tox-dev/tox/archive/refs/tags/3.24.4.tar.gz : e4afc50aaaaa74a100f8da8d193ace56eca68a5c4a5cfc3241446bc28e5d65a7
license    : MIT
component  : programming.python
summary    : Tox is a generic virtualenv management and test command line tool
description: |
    Tox is a generic virtualenv management and test command line tool
networking : yes
builddeps  :
    - py
    - pytest-runner
    - python-filelock
    - python-flaky
    - python-freezegun
    - python-packaging
    - python-pluggy
    - python-pytest-mock
    - python-setuptools-scm
    - python-six
    - python-toml
    - virtualenv
rundeps    :
    - py
    - python-filelock
    - python-packaging
    - python-pluggy
    - python-six
    - python-toml
    - virtualenv
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    python3 -m pip install tox==$version # Need python-tox installed.
    skiptest='test_parallel_inception'
    skiptest+=' or test_parallel_interrupt'          # require py2 pip
    skiptest+=' or test_create'                      # require py2 pip
    skiptest+=' or test_tox_console_script'          # require py2 pip
    skiptest+=' or test_tox_quickstart_script'
    skiptest+=' or test_parallel_error_report'       # require py2 pip
    skiptest+=' or test_parallel_show_output'        # require py2 pip
    skiptest+=' or test_provision_cli_args_ignore'
    skiptest+=' or test_provision_non_canonical_dep'
    %python3_test pytest3 -k "not (${skiptest})"
