name       : python-tox
version    : 3.22.0
release    : 10
source     :
    - https://github.com/tox-dev/tox/archive/3.22.0.tar.gz : 18692fbf5384b6ad1db72acad3775ab9098e022db4890b4f52cc5f2152892c4d
license    : MIT
component  : programming.python
summary    : Tox is a generic virtualenv management and test command line tool
description: |
    Tox is a generic virtualenv management and test command line tool
builddeps  :
    - py
    - pytest-runner
    - python-filelock
    - python-flaky
    - python-freezegun
    - python-packaging
    - python-pluggy
    - python-pytest-mock
    - python-setuptools-scm
    - python-six
    - python-toml
    - virtualenv
rundeps    :
    - py
    - python-filelock
    - python-packaging
    - python-pluggy
    - python-six
    - python-toml
    - virtualenv
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3
