name       : python-tox
version    : '3.14'
release    : 7
source     :
    - https://github.com/tox-dev/tox/archive/3.14.0.tar.gz : 334fe5c91255864e6444c6e0f1893fdf8525c12dff8ce02ea4b6b1d7d63e3cb6
license    : MIT
component  : programming.python
summary    : Tox is a generic virtualenv management and test command line tool
description: |
    Tox is a generic virtualenv management and test command line tool
builddeps  :
    - py
    - pytest-runner
    - python-filelock
    - python-flaky
    - python-freezegun
    - python-packaging
    - python-pluggy
    - python-pytest-mock
    - python-setuptools
    - python-setuptools-scm
    - python-six
    - python-toml
    - virtualenv
rundeps    :
    - py
    - python-filelock
    - python-packaging
    - python-pluggy
    - python-setuptools
    - python-six
    - python-toml
    - virtualenv
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
#check      : |
#    # wants to be tested against itself, could use virtualenv.
#    %python_test pytest
#    %python3_test pytest3
