name       : python-tox
version    : 3.5.2
release    : 5
source     :
    - https://files.pythonhosted.org/packages/38/ab/3674069bb1dadcd23e2e76c133cfa806026e68c97510224b3726562a8c44/tox-3.5.2.tar.gz : 4baeb3d8ebdcd9f43afce38aa67d06f1165a87d221d5bb21e8b39a0d4880c134
license    : MIT
component  : programming.python
summary    : Tox is a generic virtualenv management and test command line tool
description: |
    Tox is a generic virtualenv management and test command line tool
builddeps  :
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - py
    - python-filelock
    - python-packaging
    - python-pluggy
    - python-setuptools
    - python-six
    - python-toml
    - virtualenv
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
